[project]
authors = [{ name = "gitgernit", email = "petr.zakharov.anton@gmail.com" }]
name = "boilergram"
version = "0.1.0"
description = "boilergram is a superset tool that helps you develop your aiogram bots with ease using a django-like declarative approach"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = ["asyncio", "telegram", "aiogram", "django"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "aiogram>=3.5.0",
    "typer>=0.12.3",
]

[project.urls]
"Homepage" = "https://github.com/gitgernit/boilergram"
"Issues" = "https://github.com/gitgernit/boilergram/issues"

[project.scripts]
boilergram = "boilergram.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = true
managed = true
dev-dependencies = [
    "pre-commit>=3.8.0",
    "ruff>=0.5.7",
    "isort>=5.13.2",
    "pytest>=8.3.3",
    "pytest-cov>=5.0.0",
    "twine>=5.1.1",
]
