name: Publish to PyPi

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11', '3.12' ]
        poetry-version: [ '1.8' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Publish to PyPi
        run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN_BOILERGRAM: ${{ secrets.PYPI_TOKEN }}
